experiment:
  name: "Xray9_r50pre_CE"
  start_epoch: 1
  total_epochs: 100
  log_fname: "train.log"
  resume: False
  resume_fpath: "last.pth.tar"
  save_period: 10
  eval_period: 1  # if 0, remove validate process when training.

finetune:
  name: "last_DRW"
  total_epochs: 10
  unfreeze_keys: ["fc"]
  trainloader:
    sampler: ""
    retain_epoch_size: True
    batch_size: 32
    num_workers: 8
  loss:
    name: "CrossEntropyLoss"
    param:
      weight_type: "inverse"
      label_smoothing: 0.
  optimizer:
    name: "SGD"
    param:
      lr: 1.0e-2
      weight_decay: 1.0e-5
      momentum: 0.9
      nesterov: True
  lr_scheduler:
    name: 'CosineAnnealingLR'
    param:
      warmup_epochs: 0
      T_max: 10
      eta_min: 1.0e-6

train_transform:
  name: "MedTransform"
  param:
    phase: "train"
    resize: [224, 224]

val_transform:
  name: "MedTransform"
  param:
    phase: "val"
    resize: [224, 224]

train_dataset:
  name: "Xray9"
  param:
    phase: 'train'
    root: 'Xray14'
    fold_i: 0

val_dataset:
  name: "Xray9"
  param:
    phase: 'test'
    root: 'Xray14'
    fold_i: 0

# test_dataset:
#   name: ""
#   param:
#     phase: 'test'
#     root: ''

trainloader:
  sampler: ''
  batch_size: 64
  num_workers: 6

valloader:
  sampler: ''
  batch_size: 64
  num_workers: 6

# testloader:
#   sampler: ''
#   batch_size: 128
#   num_workers: 4

network:
  name: "ResNet50"
  param:
    pretrained: True
    pretrained_fpath: "~/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth"

loss:
  name: "CrossEntropyLoss"
  param:
    weight_type: ''
    label_smoothing: 0.

optimizer:
  name: "SGD"
  param:
    lr: 0.001
    weight_decay: 5.0e-4
    momentum: 0.9
    nesterov: True

lr_scheduler:
  name: "CosineAnnealingLR"
  param:
    warmup_epochs: 5
    T_max: 95
    eta_min: 1.0e-6
