# Template train config
experiment:
  name: "20211012_CIFAR10_randaug_m11n2"
  start_epoch: 1
  total_epochs: 300
  log_fname: "train.log"
  resume: False
  resume_fpath: ""
  save_period: 10
  eval_period: 1  # if 0, remove validate process when training.

train_transform:
  script_path: "data_loader.transform.transform"
  name: "RandTransform"
  param:
    phase: "train"
    resize: [32, 32]
    rand_n: 2
    rand_m: 11

eval_transform:
  script_path: "data_loader.transform.transform"
  name: "RandTransform"
  param:
    phase: "test"
    resize: [32, 32]
    rand_n: 2
    rand_m: 11

train_dataset:
  name: "CIFAR10"
  param:
    data_root: "CIFAR10"
    train: True
    img_lst_fpath: "None"
    map_fpath: "None"
    # imb_type: 'exp'
    # imb_factor: 0.01
    # rand_seed: 0
    # adapt_transform: False
    # download: False

eval_dataset:
  name: "CIFAR10"
  param:
    data_root: "CIFAR10" # default: same as train_dataset
    train: False
    img_lst_fpath: "None"
    map_fpath: "None" # default: same as train_dataset
    adapt_transform: False
    download: False

trainloader:
  name: "Dataloader"
  param:
    sampler: None
    batch_size: 64
    num_workers: 8

evalloader:
  name: "Dataloader"
  param:
    batch_size: 64
    num_workers: 8

network:
  name: "ResNet32_CIFAR"
  param:
    num_classes: 10
    pretrained: False
    pretrained_fpath: ""

loss:
  name: "CrossEntropyLoss"
  param:
    a: 0.1

optimizer:
  name: "SGD"
  param:
    lr: 0.1
    weight_decay: 5.0e-4
    momentum: 0.9
    nesterov: True

warmup_lr_scheduler:
  warmup: True
  param:
    warmup_epochs: 10
    multiplier: 1

lr_scheduler:
  # name: "CyclicLR"
  # name: "StepLR"
  name: "MultiStepLR"
  # name: "CosineAnnealingWarmRestarts"
  param:
    # CyclicLR
    # step_size_up: 3  # 3 * iterations
    # step_size_down: 2  # 2 * iterations
    # max_lr: 5.0e-2
    # base_lr: 5.0e-7
    
    # MultiStepLR
    milestones: [100, 160, 200, 240, 280]
    gamma: 0.1

    # CosineAnnealingWarmRestarts
    # T_0: 5
    # T_mult: 1
    # eta_min: 0
