experiment:
  name: "Skin7_r50_CE_0.1center"
  start_epoch: 1
  total_epochs: 200
  log_fname: "train.log"
  resume: False
  resume_fpath: "last.pth.tar"
  extract_phase: 'train'
  save_period: 10
  eval_period: 1  # if 0, remove validate process when training.

finetune:
  name: "DRW"
  total_epochs: 10
  unfreeze_keys: ["fc"]
  trainloader:
    sampler: ""
    retain_epoch_size: False
    batch_size: 64
    num_workers: 4
  network:
    name: ''
    param:
      in_channels: 64
      num_classes: 7
  loss:
    name: "CrossEntropyLoss"
    param:
      weight_type: "class_weight"
      label_smoothing: 0.
  optimizer:
    name: "SGD"
    param:
      lr: 1.0e-1
      weight_decay: 2.0e-4
      momentum: 0.9
      nesterov: True
  lr_scheduler:
    name: 'StepLR'
    param:
      warmup_epochs: 5
      step_size: 2
      # milestones: [5, 10, 15, 20]
      gamma: 0.1

train_transform:
  name: "MedTransform"
  param:
    phase: "train"
    resize: [224, 224]

val_transform:
  name: "MedTransform"
  param:
    phase: "val"
    resize: [224, 224]

# test_transform:
#   name: "MedTransform"
#   param:
#     phase: "test"
#     resize: [224, 224]

train_dataset:
  name: "Skin7"
  param:
    phase: 'train'
    root: 'Skin7'
    fold_i: 0
    # txt: '/home/19/chenghua/Projects/classification/data_loader/data/ImageNet_LT/ImageNet_LT_train.txt'
    # map_fpath: '/home/19/chenghua/Projects/classification/data_loader/data/ImageNet_LT/map.npy'
    # train: True
    # img_lst_fpath: "None"
    # map_fpath: "None"
    # imb_type: 'exp'

val_dataset:
  name: "Skin7"
  param:
    phase: 'test'
    root: 'Skin7'
    fold_i: 0
    # txt: '/home/19/chenghua/Projects/classification/data_loader/data/ImageNet_LT/ImageNet_LT_val.txt'
    # map_fpath: '/home/19/chenghua/Projects/classification/data_loader/data/ImageNet_LT/map.npy'
    # train: True
    # img_lst_fpath: "None"
    # map_fpath: "None"
    # imb_type: 'exp'

trainloader:
  sampler: ''
  batch_size: 64
  num_workers: 4

valloader:
  batch_size: 64
  num_workers: 4

network:
  name: "ResNet50"
  param:
    pretrained: False
    pretrained_fpath: ""

loss:
  name: "CrossEntropyLoss"
  param:
    weight_type: ''
    # label_smoothing: 0.

optimizer:
  name: "SGD"
  param:
    lr: 0.1
    weight_decay: 1.0e-4
    momentum: 0.9
    nesterov: True

loss2:
  name: "CenterLoss"
  param:
    weight_type: ''
    num_class: 7
    feat_dim: 2048
    alpha: 0
    lambda: 0.1

optimizer2:
  name: "SGD"
  param:
    lr: 0.5
    weight_decay: 1.0e-4
    momentum: 0.9
    nesterov: True

lr_scheduler:
  # name: "CyclicLR"
  # name: "StepLR"
  # name: "MultiStepLR"
  # name: "CosineAnnealingWarmRestarts"
  name: "CosineAnnealingLR"
  param:
    warmup_epochs: 5
    # CosineAnnealingLR
    T_max: 195
    eta_min: 0

    # CyclicLR
    # step_size_up: 3  # 3 * iterations
    # step_size_down: 2  # 2 * iterations
    # max_lr: 5.0e-2
    # base_lr: 5.0e-7

    # MultiStepLR
    # milestones: [120, 160]
    # gamma: 0.01

    # CosineAnnealingWarmRestarts
    # T_0: 5
    # T_mult: 1
    # eta_min: 0

lr_scheduler2:
  # name: "CyclicLR"
  # name: "StepLR"
  # name: "MultiStepLR"
  # name: "CosineAnnealingWarmRestarts"
  name: "CosineAnnealingLR"
  param:
    warmup_epochs: 5
    # CosineAnnealingLR
    T_max: 300  # keep a relative high learning rate
    eta_min: 0

    # CyclicLR
    # step_size_up: 3  # 3 * iterations
    # step_size_down: 2  # 2 * iterations
    # max_lr: 5.0e-2
    # base_lr: 5.0e-7

    # MultiStepLR
    # milestones: [120, 160]
    # gamma: 0.1
