experiment:
  name: Dogs_0.1_r50_smcm
  start_epoch: 1
  total_epochs: 200
  log_fname: train.log
  resume: False
  resume_fpath: last.pth.tar
  save_period: 10
  eval_period: 1  # if 0, remove validate process when training.

finetune:
  name: last_cRW
  total_epochs: 10
  unfreeze_keys: ["fc"]
  trainloader:
    sampler: ""
    batch_size: 32
    num_workers: 4
  loss:
    name: CrossEntropyLoss
    param:
      weight_type: inverse
      label_smoothing: 0.
  optimizer:
    name: SGD
    param:
      lr: 1.0e-2
      weight_decay: 1.0e-4
      momentum: 0.9
      nesterov: True
  lr_scheduler:
    name: CosineAnnealingLR
    param:
      warmup_epochs: 0
      T_max: 10
      eta_min: 1.0e-6

train_transform:
  name: MedTransform
  param:
    phase: train
    resize: [224, 224]

val_transform:
  name: MedTransform
  param:
    phase: val
    resize: [224, 224]

train_dataset:
  name: Imbalance_StanfordDogs
  param:
    phase: train
    imb_type: 'exp'
    imb_factor: 0.1
    seed: 0

val_dataset:
  name: Imbalance_StanfordDogs
  param:
    phase: test

# test_dataset:
#   name: 
#   param:
#     phase: test
#     root: 

cutmix:
  adapt_type: 2
  remix_type: 1
  kappa: 3
  mu: 0.4
  
trainloader:
  sampler: ""
  batch_size: 32
  num_workers: 8

valloader:
  sampler: ""
  batch_size: 32
  num_workers: 8

# testloader:
#   sampler: 
#   batch_size: 128
#   num_workers: 4

network:
  name: ResNet50
  param:
    pretrained: False

loss:
  name: CrossEntropyLoss
  param:
    weight_type: ""
    label_smoothing: 0.


optimizer:
  name: SGD
  param:
    lr: 0.01
    weight_decay: 5.0e-4
    momentum: 0.9
    nesterov: True

lr_scheduler:
  name: CosineAnnealingLR
  param:
    warmup_epochs: 5
    T_max: 195
    eta_min: 1.0e-6
